/*

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

*/

function generatePentagonal(num){
    const data = [];
    for(let i=1; i<=num; i++){
        data.push(i * (3 * i - 1) / 2);
    }
    return data;
}
//console.log(generatePentagonal(10));

function isPentagonal(number, penSet){
    return penSet.has(number);
}

function pentagonal(){

    const generateData = generatePentagonal(10000);
    const pentagonalSet = new Set(generateData);

    for(let j=0; j<generateData.length; j++){
        for(let k=j + 1; k<=generateData.length; k++){
            let sum = generateData[j] + generateData[k];
            let difference = generateData[k] - generateData[j];

            if(isPentagonal(sum, pentagonalSet) && isPentagonal(difference, pentagonalSet)){
                console.log(difference);
                return difference;
            }
        }
    }

}

pentagonal();